global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'observabilidade063@gmail.com'
  smtp_auth_username: 'observabilidade063@gmail.com'
  smtp_auth_password: 'Brasil@2024'
  smtp_require_tls: true

route:
  receiver: 'email_receiver'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'email_receiver'
    email_configs:
      - to: 'observabilidade063@gmail.com'
        send_resolved: true
